<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'code' => 'BRG001',
                'plu' => '1001',
                'name' => 'Laptop Asus ROG',
                'unit' => 'pcs',
                'buy_price' => 15000000,
                'sell_price' => 18000000,
                'supplier' => 'PT Maju Jaya',
                'stock' => 10,
                'department' => 'Electronics',
                'category' => 'Computer',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG002',
                'plu' => '1002',
                'name' => 'Mouse Logitech',
                'unit' => 'pcs',
                'buy_price' => 150000,
                'sell_price' => 200000,
                'supplier' => 'PT Sentosa',
                'stock' => 50,
                'department' => 'Electronics',
                'category' => 'Accessories',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG003',
                'plu' => '1003',
                'name' => 'Keyboard Mechanical',
                'unit' => 'pcs',
                'buy_price' => 500000,
                'sell_price' => 650000,
                'supplier' => 'PT Sentosa',
                'stock' => 30,
                'department' => 'Electronics',
                'category' => 'Accessories',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG004',
                'plu' => '2001',
                'name' => 'Printer Canon',
                'unit' => 'pcs',
                'buy_price' => 2000000,
                'sell_price' => 2500000,
                'supplier' => 'PT Canon Indonesia',
                'stock' => 15,
                'department' => 'Office Equipment',
                'category' => 'Printer',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG005',
                'plu' => '2002',
                'name' => 'Kertas A4 70gsm',
                'unit' => 'rim',
                'buy_price' => 35000,
                'sell_price' => 45000,
                'supplier' => 'PT Paper Indo',
                'stock' => 200,
                'department' => 'Office Supplies',
                'category' => 'Stationery',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG006',
                'plu' => '3001',
                'name' => 'Monitor LED 24"',
                'unit' => 'pcs',
                'buy_price' => 1500000,
                'sell_price' => 1900000,
                'supplier' => 'PT Maju Jaya',
                'stock' => 25,
                'department' => 'Electronics',
                'category' => 'Computer',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG007',
                'plu' => '3002',
                'name' => 'Headset Gaming',
                'unit' => 'pcs',
                'buy_price' => 300000,
                'sell_price' => 400000,
                'supplier' => 'PT Sentosa',
                'stock' => 40,
                'department' => 'Electronics',
                'category' => 'Accessories',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG008',
                'plu' => '4001',
                'name' => 'Flashdisk 32GB',
                'unit' => 'pcs',
                'buy_price' => 75000,
                'sell_price' => 100000,
                'supplier' => 'PT Tech Store',
                'stock' => 100,
                'department' => 'Electronics',
                'category' => 'Storage',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG009',
                'plu' => '4002',
                'name' => 'External HDD 1TB',
                'unit' => 'pcs',
                'buy_price' => 800000,
                'sell_price' => 1000000,
                'supplier' => 'PT Tech Store',
                'stock' => 20,
                'department' => 'Electronics',
                'category' => 'Storage',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'code' => 'BRG010',
                'plu' => '5001',
                'name' => 'Tinta Printer Black',
                'unit' => 'pcs',
                'buy_price' => 150000,
                'sell_price' => 200000,
                'supplier' => 'PT Canon Indonesia',
                'stock' => 50,
                'department' => 'Office Supplies',
                'category' => 'Consumables',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
